locker/api/urls.py
from django.urls import path, include

from . import views

app_name = 'api'

client = [
    path('<int:pk>/branch/json/', views.ClientBranchJson.as_view(), name='branch_json'),
]

calc = [
]

urlpatterns = [
    path('user/autocomplete', views.UserListJson.as_view(), name='user_autocomplete'),
    path('client/', include((client, 'client'))),
    path('calc/', include((calc, 'calc'))),
]

locker/client/urls.py
from django.urls import path, include

from calc.views import OrderCreate

from . import views

app_name = 'client'

branch = [
    path('', views.BranchListClient.as_view(), name='list'),
    path('create/', views.BranchCreate.as_view(), name='create'),
    path('<int:pk>/', views.BranchDetail.as_view(), name='detail'),
    path('<int:pk>/update/', views.BranchUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.BranchDelete.as_view(), name='delete'),
    path('<int:branch_pk>/estimate/create/', OrderCreate.as_view(), name='order_create'),
]

urlpatterns = [
    path('', views.ClientList.as_view(), name='list'),
    path('branch/', views.BranchList.as_view(), name='branch'),
    path('create/', views.ClientCreate.as_view(), name='create'),
    path('<slug:slug>/', views.ClientDetail.as_view(), name='detail'),
    path('<slug:slug>/update/', views.ClientUpdate.as_view(), name='update'),
    path('<slug:slug>/delete/', views.ClientDelete.as_view(), name='delete'),
    path('<slug:client_slug>/estimate/create/', OrderCreate.as_view(), name='order_create'),
    path('<slug:client_slug>/branch/', include((branch, 'branch'))),
]

locker/locker/urls.py
from django.contrib import admin
from django.urls import path, include, register_converter
from django.conf import settings
from django.views.generic import TemplateView, RedirectView

from core.converters import RussianSlugConverter

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.site_title = settings.ADMIN_SITE_TITLE
admin.site.index_title = settings.ADMIN_INDEX_TITLE

register_converter(RussianSlugConverter, 'slug')

urlpatterns = [
    path('', RedirectView.as_view(
        pattern_name='calc:order:list',
        permanent=False)),
    path('client/', include('client.urls')),
    path('calc/', include('calc.urls')),
    path('api/', include('api.urls')),
    path('underconstruction/', TemplateView.as_view(
        template_name='site/underconstruction.html'),
        name='underconstruction'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

# Подключение django debug toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

locker/client/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.utils.translation import pgettext_lazy
from django.core.validators import validate_unicode_slug

from core.validators import validate_slug
from core.utils import get_unique_slug

# Create your models here.

class ClientManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().prefetch_related(
            'branches', 'orders',
        ).annotate(
            number_of_orders=models.Count('orders', distinct=True),
        ).annotate(
            number_of_branches=models.Count('branches', distinct=True)
        )


class Client(models.Model):
    name = models.CharField(
        max_length=120,
        unique=True,
        verbose_name=pgettext_lazy('Client name', 'Name'),
    )
    slug = models.SlugField(
        max_length=120,
        unique=True,
        editable=False,
        allow_unicode=True,
        validators=[
            validate_unicode_slug,
            validate_slug,
        ],
        help_text=_('A label for URL config.'),
    )
    details = models.TextField(
        null=False,
        blank=False,
        verbose_name=_('Information'),
    )

    objects = ClientManager()

    class Meta:
        verbose_name = _('Client')
        verbose_name_plural = _('Clients')
        ordering = ['name', ]

    def __str__(self):
        return "{name}".format(
            name=self.name,
        )

    def save(self, *args, **kwargs):
        self.slug = get_unique_slug(self, 'slug', 'name', unique=True)
        super(Client, self).save(*args, **kwargs)

    @property
    def number_of_branches(self):
        return self.branches.count()

    @number_of_branches.setter
    def number_of_branches(self, value):
        pass

    @property
    def number_of_orders(self):
        return self.orders.count()

    @number_of_orders.setter
    def number_of_orders(self, value):
        pass

    def get_orders(self):
        return self.orders.all()

    def get_branches(self):
        return self.branches.all()

    def get_absolute_url(self):
        return reverse(
            'client:detail',
            kwargs={'slug': self.slug},
        )

    def get_update_url(self):
        return reverse(
            'client:update',
            kwargs={'slug': self.slug},
        )

    def get_delete_url(self):
        return reverse(
            'client:delete',
            kwargs={'slug': self.slug},
        )


class BranchManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().select_related(
            'client',
        ).prefetch_related(
            'orders',
        ).annotate(
            number_of_orders=models.Count('orders'),
        )


class Branch(models.Model):
    client = models.ForeignKey(
        Client,
        null=False,
        blank=False,
        on_delete=models.PROTECT,
        related_name='branches',
        verbose_name=_('Client'),
    )
    name = models.CharField(
        max_length=120,
        null=False,
        blank=False,
        verbose_name=_('Name'),
    )
    settlement = models.CharField(
        max_length=120,
        null=False,
        blank=False,
        verbose_name=_('Settlement'),
    )
    address = models.TextField(
        null=False,
        blank=False,
        verbose_name=_('Address'),
    )

    objects = BranchManager()

    class Meta:
        verbose_name = _('Branch')
        verbose_name_plural = _('Branches')
        ordering = ['client', 'name']
        unique_together = (('client', 'name', 'settlement', 'address'),)

    def __str__(self):
        return "{name}: {address} ({client})".format(
            name=self.name,
            address=', '.join((self.settlement, self.address)),
            client=self.client.name,
        )

    @property
    def number_of_orders(self):
        return self.orders.count()

    @number_of_orders.setter
    def number_of_orders(self, value):
        pass

    def get_orders(self):
        return self.orders.all()

    def get_absolute_url(self):
        return reverse(
            'client:branch:detail',
            kwargs={
                'pk': self.pk,
                'client_slug': self.client.slug,
            },
        )

    def get_update_url(self):
        return reverse(
            'client:branch:update',
            kwargs={
                'pk': self.pk,
                'client_slug': self.client.slug,
            },
        )

    def get_delete_url(self):
        return reverse(
            'client:branch:delete',
            kwargs={
                'pk': self.pk,
                'client_slug': self.client.slug,
            },
        )

locker/client/forms.py
from django import forms
from django.forms.widgets import HiddenInput

from .models import Client, Branch


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = '__all__'
        exclude = ('slug', )


class BranchForm(forms.ModelForm):
    class Meta:
        model = Branch
        fields = '__all__'
        widgets = {'client': HiddenInput()}

locker/client/views.py
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView,
    DetailView,
    UpdateView,
    DeleteView
)

from django_tables2 import SingleTableView, SingleTableMixin, MultiTableMixin
from django_filters.views import FilterView

from core.views import ActionTableDeleteMixin, DeleteMessageMixin
from calc.tables import OrderTable
from calc.models import Order

from .models import Client, Branch
from .tables import ClientTable, BranchTable
from .forms import ClientForm, BranchForm
from .filters import ClientFilter, BranchFilter
from .utils import ClientContextMixin, BranchGetObjectMixin


class ClientList(SingleTableMixin, ActionTableDeleteMixin, FilterView):
    model = Client
    table_class = ClientTable
    table_pagination = False
    filterset_class = ClientFilter
    template_name = 'client/client_list.html'
    action_table_model = Client
    action_table_success_message = _("Clients were deleted successfuly")


class ClientCreate(CreateView):
    model = Client
    form_class = ClientForm


class ClientDetail(MultiTableMixin, ActionTableDeleteMixin, DetailView):
    model = Client
    form_class = ClientForm
    action_table_multitables = [
        {
            'model': Order,
            'button': 'action-table-button',
            'success_message': _("Estimates were deleted successfuly"),
        },
        {
            'model': Branch,
            'button': 'branch-table-button',
            'success_message': _("Branches were deleted successfuly"),
        },
    ]

    def get_tables(self):
        orders = self.object.get_orders()
        orders_exclude_columns = ['client', ]

        if not self.request.user.is_superuser:
            orders = orders.filter(author=self.request.user)
            orders_exclude_columns.append('author')

        self.tables = [
            OrderTable(orders, exclude=orders_exclude_columns),
            BranchTable(self.object.get_branches(), exclude=('client', )),
        ]
        tables = super(ClientDetail, self).get_tables()
        return tables


class ClientUpdate(UpdateView):
    model = Client
    form_class = ClientForm


class ClientDelete(DeleteMessageMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('client:list')
    success_message = _("Client was deleted successfuly")


class BranchList(
        SingleTableMixin,
        ActionTableDeleteMixin,
        FilterView,
):
    model = Branch
    table_class = BranchTable
    table_pagination = False
    filterset_class = BranchFilter
    template_name = 'client/branch_list.html'
    action_table_model = Branch
    action_table_button = 'branch-table-button'
    action_table_success_message = _("Branches were deleted successfuly")


class BranchListClient(
        BranchGetObjectMixin,
        ClientContextMixin,
        SingleTableView,
        ActionTableDeleteMixin,
):
    model = Branch
    table_class = BranchTable
    template_name = 'client/branch_list.html'
    action_table_model = Branch
    action_table_button = 'branch-table-button'
    action_table_success_message = _("Branches were deleted successfuly")

    def get_table_data(self):
        client_slug = self.kwargs.get(self.client_slug_url_kwarg)
        client = Client.objects.get(slug__iexact=client_slug)
        return client.get_branches()


class BranchCreate(BranchGetObjectMixin, ClientContextMixin, CreateView):
    model = Branch
    form_class = BranchForm

    def get_initial(self):
        """Добавляет ассоциированный с branch client
        в контекст представления
        """
        # Получаем ассоциированный client
        client_slug = self.kwargs.get(self.client_slug_url_kwarg)
        self.client = get_object_or_404(Client, slug__iexact=client_slug)
        # Добавляем к начальным данным представления
        initial = {self.client_context_object_name: self.client, }
        initial.update(self.initial)
        return initial


class BranchDetail(
        BranchGetObjectMixin,
        ClientContextMixin,
        SingleTableMixin,
        ActionTableDeleteMixin,
        DetailView,
):
    model = Branch
    form_class = BranchForm
    table_class = OrderTable
    table_pagination = False
    action_table_model = Order
    action_table_success_message = _("Estimates were deleted successfuly")

    def get_table_kwargs(self):
        kwargs = {
            'exclude': ['client', 'branch', 'settlement', 'address', ]
        }

        if not self.request.user.is_superuser:
            kwargs['exclude'].append('author')

        return kwargs

    def get_table_data(self):
        client_slug = self.kwargs.get(self.client_slug_url_kwarg)
        data_filter = {
            'client__slug__iexact': client_slug,
            'branch': self.object,
        }

        if not self.request.user.is_superuser:
            data_filter['author'] = self.request.user

        return self.action_table_model.objects.filter(**data_filter)


class BranchUpdate(BranchGetObjectMixin, ClientContextMixin, UpdateView):
    model = Branch
    form_class = BranchForm


class BranchDelete(
        BranchGetObjectMixin,
        ClientContextMixin,
        DeleteMessageMixin,
        DeleteView,
):
    model = Branch
    success_message = _("Branch was deleted successfuly")

    def get_success_url(self):
        return self.object.client.get_absolute_url()

locker/client/templates/client/base_client.html
{% extends "site/base.html" %}
{% load i18n %}

{% block content %}
    <div class="row justify-content-between">
        <div class="col">
            {% block client_header %}
            {% endblock %}
        </div>
        <div class="col-auto">
            {% block client_button %}
            {% endblock %}
        </div>
    </div>
    {% block client_content %}
    {% endblock %}
{% endblock %}

locker/client/templates/client/branch_confirm_delete.html
{% extends "client/base_client.html" %}
{% load i18n %}
{% load forms %}
{% load names %}

{% block title %}
    {{ block.super }} - {% trans "Delete" %} {{ branch|verbose_name|lower }}
{% endblock %}

{% block content %}
    {% delete_form branch.get_delete_url %}
{% endblock %}

locker/client/templates/client/branch_detail.html
{% extends "client/base_client.html" %}
{% load i18n %}
{% load names %}
{% load forms %}

{% block title %}
    {{ block.super }} – {{ branch|verbose_name }}: {{ branch }}
{% endblock %}

{% block client_header %}
    <h2>{{ branch|verbose_name }}</h2>
{% endblock %}

{% block client_button %}
    <a href="{{ branch.get_update_url }}" class="btn btn-outline-primary">{% trans "Edit" %}</a>
    <a href="{{ branch.get_delete_url }}" class="btn btn-outline-secondary">{% trans "Delete" %}</a>
{% endblock %}

{% block client_content %}
    <article>
        <div class="row">
            <div class="col-5">
                <dl>
                    <dt><strong>{% field_verbose_name branch 'name' %}:</strong></dt>
                    <dd>{{ branch.name }}</dd>
                    <dt><strong>{% field_verbose_name branch 'client' %}:</strong></dt>
                    <dd><a href="{{ branch.client.get_absolute_url }}">{{ branch.client.name }}</a></dd>
                    <dt><strong>{% field_verbose_name branch 'address' %}:</strong></dt>
                    <dd>{{ branch.settlement }}, {{ branch.address }}</dd>
                    <dt><strong>{% field_verbose_name branch 'orders' %}:</strong></dt>
                    <dd>{{ branch.number_of_orders }}</dd>
                </dl>
            </div>
        </div>
        <div class="row justify-content-between">
            <div class="col">
                <h2>{% field_verbose_name branch 'orders' %}</h2>
            </div>
            <div class="col-auto">
                <a href="{% url 'client:branch:order_create' client_slug=branch.client.slug branch_pk=branch.pk %}" class="btn btn-outline-primary">{% trans "Create" %}</a>
            </div>
        </div>
        {% if table %}
            {% trans "Delete" as action_verbose %}
            {% action_table_form table button_class='btn btn-outline-secondary' action_verbose=action_verbose %}
        {% endif %}
    </article>
{% endblock %}

locker/client/templates/client/branch_form.html
{% extends "client/base_client.html" %}
{% load static %}
{% load i18n %}
{% load forms %}
{% load names %}

{% block title %}
    {{ block.super }}
    {% if branch %}
        - {% trans "Edit" %}
    {% else %}
        - {% trans "Create" %}
    {% endif %}
    {{ view.model|verbose_name|lower }}
{% endblock %}

{% block content %}
    {% if branch %}
        {% trans "Edit" as action_verbose %}
        {% form branch.get_update_url action_verbose %}
    {% else %}
        {% trans "Create" as action_verbose %}
        {% url 'client:branch:create' as form_url %}
        {% form form_url action_verbose %}
    {% endif %}
{% endblock %}

{% block body %}
    <script type="text/javascript" src="{% static 'site/js/client/branch_form.js' %}" defer></script>
{% endblock %}

locker/client/templates/client/branch_list.html
{% extends "client/base_client.html" %}
{% load static %}
{% load i18n %}
{% load django_tables2 %}
{% load names %}
{% load forms %}

{% block title %}
    {{ block.super }} - {{ view.model|verbose_name_plural }}
{% endblock %}

{% block client_header %}
    <h2>{{ view.model|verbose_name_plural }}</h2>
{% endblock %}

{% block client_button %}
    {% if filter %}
        <button class="btn btn-outline-secondary" type="button" data-toggle="collapse" data-target="#filters">{% trans 'Filters' %}</button>
    {% endif %}
    {% if client.slug %}
        <a href="{% url 'client:branch:create' client_slug=client.slug %}" class="btn btn-outline-primary">{% trans "Create" %}</a>
    {% else %}
        <a href="{% url 'client:list' %}" class="btn btn-outline-primary">{% trans "Clients" %}</a>
    {% endif %}
{% endblock %}

{% block client_content %}
    {% if filter %}
        {% filter_form filter %}
    {% endif %}
    {% if table %}
        {% trans "Delete" as action_verbose %}
        {% action_table_form table button_class='btn btn-outline-secondary' button_name='branch-table-button' button_value='branch-table-column-item' action_verbose=action_verbose %}
    {% endif %}
{% endblock %}

{% block body %}
    <script type="text/javascript" src="{% static 'site/js/client/branch_list.js' %}" defer></script>
{% endblock %}

locker/client/templates/client/client_confirm_delete.html
{% extends "client/base_client.html" %}
{% load i18n %}
{% load forms %}
{% load names %}

{% block title %}
    {{ block.super }} - {% trans "Delete" %} {{ client|verbose_name|lower }}
{% endblock %}

{% block content %}
    {% delete_form client.get_delete_url %}
{% endblock %}

locker/client/templates/client/client_detail.html
{% extends "client/base_client.html" %}
{% load i18n %}
{% load django_tables2 %}
{% load names %}
{% load forms %}

{% block title %}
    {{ block.super }} – {{ client|verbose_name }}: {{ client }}
{% endblock %}

{% block client_header %}
    <h2>{{ client|verbose_name }}</h2>
{% endblock %}

{% block client_button %}
    <a href="{{ client.get_update_url }}" class="btn btn-outline-primary">{% trans "Edit" %}</a>
    <a href="{{ client.get_delete_url }}" class="btn btn-outline-secondary">{% trans "Delete" %}</a>
{% endblock %}

{% block client_content %}
    <article>
        <div class="row">
            <div class="col-5">
                <dl>
                    <dt><strong>{% field_verbose_name client 'name' %}:</strong></dt>
                    <dd>{{ client.name }}</dd>
                    <dt><strong>{% field_verbose_name client 'details' %}:</strong></dt>
                    <dd>{{ client.details }}</dd>
                    <dt><strong>{% field_verbose_name client 'branches' %}:</strong></dt>
                    <dd>{{ client.number_of_branches }}</dd>
                    <dt><strong>{% field_verbose_name client 'orders' %}:</strong></dt>
                    <dd>{{ client.number_of_orders }}</dd>
                </dl>
            </div>
        </div>
        <div class="row justify-content-between">
            <div class="col">
                <h2>{% field_verbose_name client 'branches' %}</h2>
            </div>
            <div class="col-auto">
                <a href="{% url 'client:branch:create' client_slug=client.slug %}" class="btn btn-outline-primary">{% trans "Create" %}</a>
            </div>
        </div>
        {% if tables.1 %}
            {% trans "Delete" as action_verbose %}
            {% action_table_form tables.1 button_class='btn btn-outline-secondary' button_name='branch-table-button' button_value='branch-table-column-item' action_verbose=action_verbose %}
        {% endif %}
        <div class="row justify-content-between">
            <div class="col">
                <h2>{% field_verbose_name client 'orders' %}</h2>
            </div>
            <div class="col-auto">
                <a href="{% url 'client:order_create' client_slug=client.slug %}" class="btn btn-outline-primary">{% trans "Create" %}</a>
            </div>
        </div>
        {% if tables.0 %}
            {% trans "Delete" as action_verbose %}
            {% action_table_form tables.0 button_class='btn btn-outline-secondary' action_verbose=action_verbose %}
        {% endif %}
    </article>
{% endblock %}

locker/client/templates/client/client_form.html
{% extends "client/base_client.html" %}
{% load static %}
{% load i18n %}
{% load forms %}
{% load names %}

{% block title %}
    {{ block.super }}
    {% if client %}
        - {% trans "Edit" %}
    {% else %}
        - {% trans "Create" %}
    {% endif %}
    {{ view.model|verbose_name|lower }}
{% endblock %}

{% block content %}
    {% if client %}
        {% trans "Edit" as action_verbose %}
        {% form client.get_update_url action_verbose %}
    {% else %}
        {% trans "Create" as action_verbose %}
        {% url 'client:create' as form_url %}
        {% form form_url action_verbose %}
    {% endif %}
{% endblock %}

{% block body %}
    <script type="text/javascript" src="{% static 'site/js/client/client_form.js' %}" defer></script>
{% endblock %}

locker/client/templates/client/client_list.html
{% extends "client/base_client.html" %}
{% load static %}
{% load i18n %}
{% load django_tables2 %}
{% load names %}
{% load forms %}

{% block title %}
    {{ block.super }} - {{ view.model|verbose_name_plural }}
{% endblock %}

{% block client_header %}
    <h2>{{ view.model|verbose_name_plural }}</h2>
{% endblock %}

{% block client_button %}
    {% if filter %}
        <button class="btn btn-outline-secondary" type="button" data-toggle="collapse" data-target="#filters">{% trans 'Filters' %}</button>
    {% endif %}
    <a href="{% url 'client:create' %}" class="btn btn-outline-primary">{% trans "Create" %}</a>
{% endblock %}

{% block client_content %}
    {% if filter %}
        {% filter_form filter %}
    {% endif %}
    {% if table %}
        {% trans "Delete" as action_verbose %}
        {% action_table_form table button_class='btn btn-outline-secondary' action_verbose=action_verbose %}
    {% endif %}
{% endblock %}

{% block body %}
    <script type="text/javascript" src="{% static 'site/js/client/client_list.js' %}" defer></script>
{% endblock %}