locker/api/urls.py
from django.urls import path, include

from . import views

app_name = 'api'

client = [
    path('<int:pk>/branch/json/', views.ClientBranchJson.as_view(), name='branch_json'),
]

calc = [
]

urlpatterns = [
    path('user/autocomplete', views.UserListJson.as_view(), name='user_autocomplete'),
    path('client/', include((client, 'client'))),
    path('calc/', include((calc, 'calc'))),
]

locker/client/urls.py
from django.urls import path, include

from calc.views import OrderCreate

from . import views

app_name = 'client'

branch = [
    path('', views.BranchListClient.as_view(), name='list'),
    path('create/', views.BranchCreate.as_view(), name='create'),
    path('<int:pk>/', views.BranchDetail.as_view(), name='detail'),
    path('<int:pk>/update/', views.BranchUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.BranchDelete.as_view(), name='delete'),
    path('<int:branch_pk>/estimate/create/', OrderCreate.as_view(), name='order_create'),
]

urlpatterns = [
    path('', views.ClientList.as_view(), name='list'),
    path('branch/', views.BranchList.as_view(), name='branch'),
    path('create/', views.ClientCreate.as_view(), name='create'),
    path('<slug:slug>/', views.ClientDetail.as_view(), name='detail'),
    path('<slug:slug>/update/', views.ClientUpdate.as_view(), name='update'),
    path('<slug:slug>/delete/', views.ClientDelete.as_view(), name='delete'),
    path('<slug:client_slug>/estimate/create/', OrderCreate.as_view(), name='order_create'),
    path('<slug:client_slug>/branch/', include((branch, 'branch'))),
]

locker/locker/urls.py
from django.contrib import admin
from django.urls import path, include, register_converter
from django.conf import settings
from django.views.generic import TemplateView, RedirectView

from core.converters import RussianSlugConverter

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.site_title = settings.ADMIN_SITE_TITLE
admin.site.index_title = settings.ADMIN_INDEX_TITLE

register_converter(RussianSlugConverter, 'slug')

urlpatterns = [
    path('', RedirectView.as_view(
        pattern_name='calc:order:list',
        permanent=False)),
    path('client/', include('client.urls')),
    path('calc/', include('calc.urls')),
    path('api/', include('api.urls')),
    path('underconstruction/', TemplateView.as_view(
        template_name='site/underconstruction.html'),
        name='underconstruction'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

# Подключение django debug toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

locker/templates/site/base.html
{% load static%}
{% load i18n %}

<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <title>
            {% block title %}
                Пром-Спектр
            {% endblock %}
        </title>
        <link rel="icon" href="{% static 'site/images/favicon.ico' %}" type="image/x-icon">
        <link rel="shortcut icon" href="{% static 'site/images/favicon.ico' %}" type="image/x-icon">
        <link rel="stylesheet" type="text/css" href="{% static 'site/bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'site/jquery-ui/jquery-ui.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'site/select2/select2.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'site/select2/select2-bootstrap4.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'site/css/style.css' %}">
        <script type="text/javascript" src="{% static 'site/jquery/jquery.min.js' %}" defer></script>
        {% block head %}
        {% endblock %}
    </head>
    <body class="body">
        <header class="header">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">
                        <img src="{% static 'site/images/logo.png' %}" alt="" width="30" height="30" class="d-inline-block align-top">
                        Пром-Спектр
                    </a>
                    <!-- Toggle button -->
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <!-- Navigation menu -->
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul id="navbarMainNavigation" class="navbar-nav">
                            <li class="nav-item"><a class="nav-link" href="{% url 'calc:order:list' %}">{% trans "Estimates" %}</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'client:list' %}">{% trans "Clients" %}</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'client:branch' %}">{% trans "Branches" %}</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'calc:service:list' %}">{% trans "Equipment" %}</a></li>
                        </ul>
                    </div>
                    <!-- User menu -->
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            {% if user.is_authenticated %}
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {%  with USER_FULL_NAME=user.get_full_name %}
                                    {% if USER_FULL_NAME %}
                                        {{ USER_FULL_NAME }}
                                    {% else %}
                                        {{ user }}
                                    {% endif %}
                                {% endwith %}
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdown">
                                        <a class="dropdown-item" href="{% url 'logout' %}">{% trans "Log out" %}</a>
                                    </div>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'login' %}">{% trans "Log in" %}</a>
                                </li>
                            {% endif %}
                            <li>
                            </li>
                        </ul>
                        <!-- Language select -->
                        <form class="d-flex ml-3" action="{% url 'set_language' %}" method="post">
                            {% csrf_token %}
                            <input name="next" type="hidden" value="{{ redirect_to }}" />
                            <select name="language" onchange="this.form.submit()">
                                {% get_current_language as CURRENT_LANGUAGE  %}
                                {% get_available_languages as LANGUAGES %}
                                {% get_language_info_list for LANGUAGES as languages %}
                                {% for language in languages %}
                                    <option value="{{ language.code }}"
                                            {% if language.code == CURRENT_LANGUAGE %} selected="selected"{% endif %}>
                                    {{ language.name_local }}
                                    </option>
                                {% endfor %}
                            </select>
                        </form>
                    </div>
                </div>
            </nav>
        </header>
        <main class="main">
            <div class="loading-progress"></div>
            <div class="container" style="visibility: hidden"><!-- container -->
                <!-- Messages -->
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert
                                    {% if message.tags %}
                                        {{ message.tags }}
                                    {% endif %}
                                    alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endfor %}
                {% endif %}
                {% block content %}
                {% endblock %}
            </div><!-- container -->
        </main>
        <footer class="footer">
            {% block footer %}
            {% endblock %}
            <div class="navbar fixed-bottom navbar-dark bg-dark py-0">
                <div class="mx-auto">
                    <span class="navbar-text py-0">
                        &copy; {% now "Y" %} <a href="https://psmontag.ru/">ООО ПКФ "ПРОМ-Спектр”</a>
                    </span>
                </div>
            </div>
        </footer>
        <script type="text/javascript" src="{% static 'site/bootstrap/js/bootstrap.bundle.min.js' %}" defer></script>
        <script type="text/javascript" src="{% static 'site/jquery-ui/jquery-ui.min.js' %}" defer></script>
        <script type="text/javascript" src="{% static 'site/select2/select2.min.js' %}" defer></script>
        <script type="text/javascript" src="{% static 'site/select2/select2-ru.js' %}" defer></script>
        <script type="text/javascript" src="{% static 'site/js/base.js' %}" defer></script>
        {% block body %}
        {% endblock %}
    </body>
</html>

locker/templates/site/underconstruction.html
{% extends "site/base.html" %}
{% load i18n %}

{% block title %}
    {{ block.super }} - {% trans "Under construction" %}
{% endblock %}

{% block content %}
    <h2>{% trans "Under construction" %}</h2>

    <p>{% trans "Sorry, this section is under construction." %}</p>
{% endblock %}